name: Build and Release Wheels

on:
  push:
    tags:
      - 'v*'

jobs:
  build-packages:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - events
          - publisher
    outputs:
      # Pass artifact names for downstream job
      artifact-name: ${{ matrix.package }}-wheel

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Build ${{ matrix.package }} wheel
        working-directory: ./common/${{ matrix.package }}
        run: |
          python -m pip install --upgrade build
          python -m build --wheel

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.package }}-wheel
          path: ./common/${{ matrix.package }}/dist/*.whl

  release:
    needs: build-packages
    runs-on: ubuntu-latest

    steps:
      - name: Download events wheel
        uses: actions/download-artifact@v4
        with:
          name: events-wheel
          path: ./dist/events

      - name: Download publisher wheel
        uses: actions/download-artifact@v4
        with:
          name: publisher-wheel
          path: ./dist/publisher

      - name: Create or update GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: Automated release of built wheels.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload wheels to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./dist/events/*.whl
            ./dist/publisher/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
