name: Build and Release Wheels

on:
  push:
    tags:
      - 'events-v*'
      - 'publisher-v*'
      - 'subscriber-v*'

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Extract package name from tag
        id: extract
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          PACKAGE=${TAG%%-*}
          echo "package=$PACKAGE" >> $GITHUB_OUTPUT

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Build wheel
        working-directory: ./common/${{ steps.extract.outputs.package }}
        run: |
          python -m pip install --upgrade build
          python -m build --wheel

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: Automated release of ${{ steps.extract.outputs.package }} wheel.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload wheel to release
        uses: softprops/action-gh-release@v2
        with:
          files: ./common/${{ steps.extract.outputs.package }}/dist/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
