name: Build and upload wheels

on:
  push:
    branches:
      - main
    paths:
      - 'common/events/pyproject.toml'
      - 'common/publisher/pyproject.toml'

  workflow_dispatch:

jobs:
  build-packages:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package:
          - events
          - publisher

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Build ${{ matrix.package }} wheel
        working-directory: ./common/${{ matrix.package }}
        run: |
          python -m pip install --upgrade build
          python -m build --wheel

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.package }}-wheel
          path: ./dist/*.whl
